import { Dish } from './types';

// Tuščias patiekalų sąrašas - reikia užpildyti tikrais patiekalais
export const sampleDishes: Dish[] = [
  // SRIUBOS
  { id: '1894', name: 'Agurkinė sriuba', category: 'SRIUBOS', price: 1.70 },
  { id: '1640', name: 'Agurkinė sriuba 0,5', category: 'SRIUBOS', price: 1.00 },
  { id: '1655', name: 'Aštri sriuba', category: 'SRIUBOS', price: 2.20 },
  { id: '1572', name: 'Bulvienė', category: 'SRIUBOS', price: 1.70 },
  { id: '1573', name: 'Bulvienė 0,5', category: 'SRIUBOS', price: 1.00 },
  { id: '1604', name: 'Burokėlių sriuba', category: 'SRIUBOS', price: 1.70 },
  { id: '1889', name: 'Burokėlių sriuba 0,5', category: 'SRIUBOS', price: 1.00 },
  { id: '1647', name: 'Daržovių sriuba', category: 'SRIUBOS', price: 1.70 },
  { id: '1451', name: 'Daržovių sriuba 0,5', category: 'SRIUBOS', price: 1.00 },
  { id: '2012', name: 'Daržovių sriuba su kruopomis', category: 'SRIUBOS', price: 1.70 },
  { id: '2013', name: 'Daržovių sriuba su kruopomis 0,5', category: 'SRIUBOS', price: 1.00 },
  { id: '1967', name: 'Grybų sriuba', category: 'SRIUBOS', price: 1.70 },
  { id: '1968', name: 'Grybų sriuba 0,5', category: 'SRIUBOS', price: 1.00 },
  { id: '1530', name: 'Kopūstų sriuba', category: 'SRIUBOS', price: 1.70 },
  { id: '1644', name: 'Kopūstų sriuba 0,5', category: 'SRIUBOS', price: 1.00 },
  { id: '1907', name: 'Makaronai su frikadelėmis', category: 'SRIUBOS', price: 1.70 },
  { id: '1908', name: 'Makaronai su frikadelėmis 0,5', category: 'SRIUBOS', price: 1.00 },
  { id: '2056', name: 'Minestronė', category: 'SRIUBOS', price: 1.70 },
  { id: '2057', name: 'Minestronė 0,5', category: 'SRIUBOS', price: 1.00 },
  { id: '1646', name: 'Perlinių kruopų sriuba', category: 'SRIUBOS', price: 1.70 },
  { id: '2075', name: 'Perlinių kruopų sriuba 0,5', category: 'SRIUBOS', price: 1.00 },
  { id: '1639', name: 'Pomidorinė sriuba', category: 'SRIUBOS', price: 1.70 },
  { id: '1458', name: 'Pomidorinė sriuba 0,5', category: 'SRIUBOS', price: 1.00 },
  { id: '2006', name: 'Pupelių sriuba', category: 'SRIUBOS', price: 1.70 },
  { id: '2007', name: 'Pupelių sriuba 0,5', category: 'SRIUBOS', price: 1.00 },
  { id: '1648', name: 'Raugintų kopūstų sriuba', category: 'SRIUBOS', price: 1.70 },
  { id: '1528', name: 'Raugintų kopūstų sriuba 0,5', category: 'SRIUBOS', price: 1.00 },
  { id: '1643', name: 'Rūgštynių sriuba', category: 'SRIUBOS', price: 1.70 },
  { id: '1457', name: 'Rūgštynių sriuba 0,5', category: 'SRIUBOS', price: 1.00 },
  { id: '1930', name: 'Saldi sriuba', category: 'SRIUBOS', price: 2.20 },
  { id: '1459', name: 'Šaltibarščiai', category: 'SRIUBOS', price: 2.20 },
  { id: '2051', name: 'Trinta špinatų sriuba', category: 'SRIUBOS', price: 2.20 },
  { id: '1845', name: 'Trinta daržovių sriuba su vištiena', category: 'SRIUBOS', price: 2.20 },
  { id: '1645', name: 'Trinta daržovių sriuba', category: 'SRIUBOS', price: 2.20 },
  { id: '1649', name: 'Trinta moliūgų sriuba', category: 'SRIUBOS', price: 2.20 },
  { id: '1653', name: 'Trinta morkų sriuba', category: 'SRIUBOS', price: 2.20 },
  { id: '1652', name: 'Trinta pievagrybių sriuba', category: 'SRIUBOS', price: 2.20 },
  { id: '1650', name: 'Trinta pomidorų sriuba', category: 'SRIUBOS', price: 2.20 },
  { id: '2061', name: 'Trinta žirnių sriuba', category: 'SRIUBOS', price: 2.20 },
  { id: '1471', name: 'Ukrainietiški barščiai', category: 'SRIUBOS', price: 1.70 },
  { id: '1475', name: 'Ukrainietiški barščiai 0,5', category: 'SRIUBOS', price: 1.00 },
  { id: '1986', name: 'Vištienos sriuba', category: 'SRIUBOS', price: 1.70 },
  { id: '1987', name: 'Vištienos sriuba 0,5', category: 'SRIUBOS', price: 1.00 },
  { id: '1641', name: 'Žirnių sriuba', category: 'SRIUBOS', price: 1.70 },
  { id: '1895', name: 'Žirnių sriuba 0,5', category: 'SRIUBOS', price: 1.00 },
  { id: '1642', name: 'Žuvienė', category: 'SRIUBOS', price: 1.70 },
  { id: '1450', name: 'Žuvienė 0,5', category: 'SRIUBOS', price: 1.00 },

  // KARŠTI BULVINIAI
  { id: '1548', name: 'Blynai su česnakine varške', category: 'KARŠTI_BULVINIAI', price: 4.50 },
  { id: '1562', name: 'Blynai su česnakine varške ir lašiša', category: 'KARŠTI_BULVINIAI', price: 5.80 },
  { id: '1566', name: 'Blynai su česnakine varške ir silke', category: 'KARŠTI_BULVINIAI', price: 5.50 },
  { id: '1490', name: 'Cepelinai su varške', category: 'KARŠTI_BULVINIAI', price: 5.90 },
  { id: '1491', name: 'Cepelinai su varške 0,5', category: 'KARŠTI_BULVINIAI', price: 3.50 },
  { id: '1848', name: 'Cepelinų mix\'as (su mėsa/varške)', category: 'KARŠTI_BULVINIAI', price: 5.90 },
  { id: '1919', name: 'Cepelinų mix\'as (su mėsa/plaučiukais)', category: 'KARŠTI_BULVINIAI', price: 5.90 },
  { id: '1944', name: 'Cepelinų mix\'as (su varške/plaučiukais)', category: 'KARŠTI_BULVINIAI', price: 5.90 },
  { id: '1838', name: 'Cepelinai su mėsa', category: 'KARŠTI_BULVINIAI', price: 5.90 },
  { id: '1839', name: 'Cepelinai su mėsa 0,5', category: 'KARŠTI_BULVINIAI', price: 3.50 },
  { id: '1865', name: 'Cepelinai su plaučiukais', category: 'KARŠTI_BULVINIAI', price: 5.90 },
  { id: '1866', name: 'Cepelinai su plaučiukais 0,5', category: 'KARŠTI_BULVINIAI', price: 3.50 },
  { id: '1853', name: 'Čičinskai', category: 'KARŠTI_BULVINIAI', price: 5.70 },
  { id: '1584', name: 'Čičinskai 0,5', category: 'KARŠTI_BULVINIAI', price: 3.50 },
  { id: '1549', name: 'Didžkukuliai su mėsa', category: 'KARŠTI_BULVINIAI', price: 4.80 },
  { id: '1550', name: 'Didžkukuliai su mėsa 0,5', category: 'KARŠTI_BULVINIAI', price: 3.50 },
  { id: '1578', name: 'Didžkukuliai su varške', category: 'KARŠTI_BULVINIAI', price: 4.80 },
  { id: '1580', name: 'Didžkukuliai su varške 0,5', category: 'KARŠTI_BULVINIAI', price: 3.50 },
  { id: '1718', name: 'Didžkukulių mix\'as (su mėsa/varške)', category: 'KARŠTI_BULVINIAI', price: 4.80 },
  { id: '1872', name: 'Gruzdinti cepelinai su mėsa', category: 'KARŠTI_BULVINIAI', price: 5.90 },
  { id: '1873', name: 'Gruzdinti cepelinai su mėsa 0,5', category: 'KARŠTI_BULVINIAI', price: 3.50 },
  { id: '1874', name: 'Gruzdinti cepelinai su varške', category: 'KARŠTI_BULVINIAI', price: 5.90 },
  { id: '1875', name: 'Gruzdinti cepelinai su varške 0,5', category: 'KARŠTI_BULVINIAI', price: 3.50 },
  { id: '1950', name: 'Gruzdintų cepelinų mix\'as (su mėsa/varške)', category: 'KARŠTI_BULVINIAI', price: 5.90 },
  { id: '1943', name: 'Gruzdintas plokštainis su ausytėmis', category: 'KARŠTI_BULVINIAI', price: 5.50 },
  { id: '1876', name: 'Gruzdintas plokštainis', category: 'KARŠTI_BULVINIAI', price: 4.80 },
  { id: '2029', name: 'Gruzdintas plokštainis su vištiena', category: 'KARŠTI_BULVINIAI', price: 5.20 },
  { id: '1870', name: 'Pievagrybiais ir šonine įdaryti bulviniai rageliai', category: 'KARŠTI_BULVINIAI', price: 4.00 },
  { id: '1871', name: 'Pievagrybiais ir šonine įdaryti bulviniai rageliai 0,5', category: 'KARŠTI_BULVINIAI', price: 2.80 },
  { id: '1559', name: 'Kėdainių blynai', category: 'KARŠTI_BULVINIAI', price: 5.90 },
  { id: '1560', name: 'Kėdainių blynai 0,5', category: 'KARŠTI_BULVINIAI', price: 3.50 },
  { id: '1851', name: 'Bulvių ir varškės kukulaičiai', category: 'KARŠTI_BULVINIAI', price: 4.30 },
  { id: '1852', name: 'Bulvių ir varškės kukulaičiai 0,5', category: 'KARŠTI_BULVINIAI', price: 3.20 },
  { id: '1900', name: 'Plokštainis su karka', category: 'KARŠTI_BULVINIAI', price: 5.50 },
  { id: '1933', name: 'Plokštainis su ausytėmis', category: 'KARŠTI_BULVINIAI', price: 5.50 },
  { id: '1568', name: 'Plokštainis su vištiena', category: 'KARŠTI_BULVINIAI', price: 5.20 },
  { id: '1547', name: 'Plokštainis', category: 'KARŠTI_BULVINIAI', price: 4.80 },
  { id: '1492', name: 'Švilpikai', category: 'KARŠTI_BULVINIAI', price: 4.40 },
  { id: '1545', name: 'Vėdarai', category: 'KARŠTI_BULVINIAI', price: 5.00 },
  { id: '1980', name: 'Žemaičių blynai su plaučiukais', category: 'KARŠTI_BULVINIAI', price: 5.90 },
  { id: '1981', name: 'Žemaičių blynai su plaučiukais 0,5', category: 'KARŠTI_BULVINIAI', price: 3.50 },
  { id: '1499', name: 'Žemaičių blynai su mėsa', category: 'KARŠTI_BULVINIAI', price: 5.90 },
  { id: '1526', name: 'Žemaičių blynai su mėsa', category: 'KARŠTI_BULVINIAI', price: 3.50 },
  { id: '2058', name: 'Žemaičių blynai su varške', category: 'KARŠTI_BULVINIAI', price: 5.90 },
  { id: '2059', name: 'Žemaičių blynai su varške', category: 'KARŠTI_BULVINIAI', price: 3.50 },

  // JAUTIENA
  { id: '1660', name: 'Aštrus troškinys su daržovėmis', category: 'KARŠTI_JAUTIENA', price: 7.60 },
  { id: '1656', name: 'Befstrogenas', category: 'KARŠTI_JAUTIENA', price: 7.60 },
  { id: '1537', name: 'Bifšteksas', category: 'KARŠTI_JAUTIENA', price: 6.50 },
  { id: '2073', name: 'Itališki maltinukai', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '2072', name: 'Itališki maltinukai 0,5', category: 'KARŠTI_JAUTIENA', price: 5.10 },
  { id: '1659', name: 'Kepenėlių troškinys su svogūnais', category: 'KARŠTI_JAUTIENA', price: 5.70 },
  { id: '1535', name: 'Kepenėlių kotletukai', category: 'KARŠTI_JAUTIENA', price: 5.40 },
  { id: '1536', name: 'Kepenėlių kotletukai 0,5', category: 'KARŠTI_JAUTIENA', price: 4.30 },
  { id: '1599', name: 'Lazanija', category: 'KARŠTI_JAUTIENA', price: 6.50 },
  { id: '1673', name: 'Maltinis  įdarytas šonine ir sūriu', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '1675', name: 'Maltinis įdarytas grybais ir sūriu', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '1678', name: 'Maltinis įdarytas špinatais ir svogūnais', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '1670', name: 'Maltinis įdatytas morkomis ir svogūnais', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '1672', name: 'Maltinis įdarytas feta', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '1671', name: 'Maltinis įdarytas saulėje džiovintais pomidorais', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '1680', name: 'Maltinis įdarytas špinatais, apsuktas šonine', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '1681', name: 'Maltinis įdarytas grybais ir sūriu, apsuktas šonine', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '1678', name: 'Maltinis įdarytas feta, apsuktas šonine', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '1677', name: 'Maltinis įdarytas saulėje džiovintais pomidorais, apsuktas šonine', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '1676', name: 'Maltinis įdarytas morkomis ir svogūnais, apsuktas šonine', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '1679', name: 'Maltinis įdarytas šonine ir sūriu, apsuktas šonine', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '1664', name: 'Maltinukai', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '1668', name: 'Maltinukai grybų padaže', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '1744', name: 'Maltinukai grybų padaže 0,5', category: 'KARŠTI_JAUTIENA', price: 4.90 },
  { id: '1877', name: 'Maltinukai daržovių padaže', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '1878', name: 'Maltinukai daržovių padaže 0,5', category: 'KARŠTI_JAUTIENA', price: 4.90 },
  { id: '1856', name: 'Maltinukai špinatų padaže', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '1748', name: 'Maltinukai špinatų padaže 0,5', category: 'KARŠTI_JAUTIENA', price: 4.90 },
  { id: '2065', name: 'Maltinukai baltame padaže', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '2066', name: 'Maltinukai baltame padaže 0,5', category: 'KARŠTI_JAUTIENA', price: 4.90 },
  { id: '1666', name: 'Maltinukai grietinės ir pomidorų padaže', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '1745', name: 'Maltinukai grietinės ir pomidorų padaže 0,5', category: 'KARŠTI_JAUTIENA', price: 4.90 },
  { id: '1989', name: 'Maltinukai grietinėlės saldžiarūgščiame padaže', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '1990', name: 'Maltinukai grietinėlės saldžiarūgščiame padaže 0,5', category: 'KARŠTI_JAUTIENA', price: 4.90 },
  { id: '1661', name: 'Troškinys su avinžirniais', category: 'KARŠTI_JAUTIENA', price: 7.60 },
  { id: '1976', name: 'Troškinys su daržovėmis', category: 'KARŠTI_JAUTIENA', price: 7.60 },
  { id: '1663', name: 'Troškinys su saulėje džiovintais pomidorais', category: 'KARŠTI_JAUTIENA', price: 7.60 },
  { id: '1662', name: 'Troškinys su šparagais', category: 'KARŠTI_JAUTIENA', price: 7.60 },
  { id: '2047', name: 'Troškinys su šparagais/Aštrus', category: 'KARŠTI_JAUTIENA', price: 7.60 },
  { id: '1958', name: 'Troškinys su svogūnais ir pomidorų padažu', category: 'KARŠTI_JAUTIENA', price: 7.60 },
  { id: '2067', name: 'Troškinys su grybais', category: 'KARŠTI_JAUTIENA', price: 7.60 },
  { id: '1460', name: 'Troškinys su paryžietiškomis morkomis', category: 'KARŠTI_JAUTIENA', price: 7.60 },
  { id: '2125', name: 'Troškinys su slyvomis', category: 'KARŠTI_JAUTIENA', price: 7.60 },
  { id: '1684', name: 'Užkeptas maltinis su svogūnais pomidorų padaže', category: 'KARŠTI_JAUTIENA', price: 6.50 },
  { id: '1685', name: 'Užkeptas maltinis su daržovėmis', category: 'KARŠTI_JAUTIENA', price: 6.50 },
  { id: '1683', name: 'Užkeptas maltinis su grybais', category: 'KARŠTI_JAUTIENA', price: 6.50 },
  { id: '1686', name: 'Užkeptas maltinis su morkomis ir svogūnais', category: 'KARŠTI_JAUTIENA', price: 6.50 },
  { id: '1682', name: 'Užkeptas maltinis su marinuotais svogūnais', category: 'KARŠTI_JAUTIENA', price: 6.50 },
  { id: '1687', name: 'Užkeptas maltinis su šviežiomis morkomis', category: 'KARŠTI_JAUTIENA', price: 6.50 },
  { id: '1476', name: 'Zrazai įdarytas grybais baltame padaže', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '1488', name: 'Zrazai įdarytas grybais baltame padaže 0,5', category: 'KARŠTI_JAUTIENA', price: 4.90 },
  { id: '2124', name: 'Guliašas', category: 'KARŠTI_JAUTIENA', price: 7.60 },
  { id: '1551', name: 'Maltinis', category: 'KARŠTI_JAUTIENA', price: 6.30 },
  { id: '1565', name: 'Kepenėlių troškinys su grietinės ir pomidorų padažu', category: 'KARŠTI_JAUTIENA', price: 5.90 },

  // KIAULIENA
  { id: '1940', name: 'Aštrūs kiaulienos vėrinukai', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1539', name: 'Balandėliai', category: 'KARŠTI_KIAULIENA', price: 5.00 },
  { id: '1540', name: 'Balandėliai 0,5', category: 'KARŠTI_KIAULIENA', price: 7.00 },
  { id: '1869', name: 'Dešrelės', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1466', name: 'Guliašas', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '2008', name: 'Guliašas su morkomis', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1946', name: 'Įdaryta nugarinė morkomis ir svogūnais traškia plutele', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '2004', name: 'Įdaryta nugarinė feta traškia plutele', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1555', name: 'Įdaryta nugarinė feta ir saulėje džiovintais pomidorais traškia plutele', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1557', name: 'Įdaryta nugarinė feta ir špinatais traškia plutele', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1574', name: 'Įdaryta nugarinė grybais ir sūriu traškia plutele', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '2010', name: 'Įdaryta nugarinė šonine ir sūriu traškia plutele', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '2016', name: 'Įdaryta paprika', category: 'KARŠTI_KIAULIENA', price: 5.70 },
  { id: '2062', name: 'Įdaryta paprika 0,5', category: 'KARŠTI_KIAULIENA', price: 4.20 },
  { id: '1857', name: 'Kiauliena kinietiškai', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1692', name: 'Kiauliena meksikietiškai', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1456', name: 'Kepsnys', category: 'KARŠTI_KIAULIENA', price: 5.90 },
  { id: '1464', name: 'Kepsnys su grybų padažu', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1708', name: 'Kepsnys užkeptas svogūnais pomidorų padaže', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1707', name: 'Kepsnys užkeptas grybais ir svogūnais', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1706', name: 'Kepsnys užkeptas morkomis ir svogūnais', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1711', name: 'Kepsnys užkeptas šv.morkomis', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1737', name: 'Maltinis įdarytas morkomis, apsuktas šonine', category: 'KARŠTI_KIAULIENA', price: 5.70 },
  { id: '1739', name: 'Maltinis įdarytas šonine ir sūriu, apsuktas šonine', category: 'KARŠTI_KIAULIENA', price: 5.70 },
  { id: '1740', name: 'Maltinis įdarytas špinatais, apsuktas šonine', category: 'KARŠTI_KIAULIENA', price: 5.70 },
  { id: '1739', name: 'Maltinis įdarytas saulėje džiovintais pomidorais, apsuktas šonine', category: 'KARŠTI_KIAULIENA', price: 5.70 },
  { id: '1741', name: 'Maltinis įdarytas grybais ir sūriu, apsuktas šonine', category: 'KARŠTI_KIAULIENA', price: 5.70 },
  { id: '1699', name: 'Maltinis įdarytas feta', category: 'KARŠTI_KIAULIENA', price: 5.40 },
  { id: '1952', name: 'Maltinis įdaytas špinatais', category: 'KARŠTI_KIAULIENA', price: 5.40 },
  { id: '1735', name: 'Maltinis įdarytas grybais ir sūriu', category: 'KARŠTI_KIAULIENA', price: 5.40 },
  { id: '1969', name: 'Maltinis įdarytas feta, baltame padaže', category: 'KARŠTI_KIAULIENA', price: 5.70 },
  { id: '1541', name: 'Maltinis špinatų padaže', category: 'KARŠTI_KIAULIENA', price: 5.40 },
  { id: '1729', name: 'Maltinis baltame padaže', category: 'KARŠTI_KIAULIENA', price: 5.40 },
  { id: '1697', name: 'Maltinis grybų padaže', category: 'KARŠTI_KIAULIENA', price: 6.00 },
  { id: '1701', name: 'Maltinis užkeptas grybais ir mocarela', category: 'KARŠTI_KIAULIENA', price: 6.00 },
  { id: '1880', name: 'Maltinis užkeptas marinuotais svogūnais ir mocarela', category: 'KARŠTI_KIAULIENA', price: 6.00 },
  { id: '1703', name: 'Maltinis užkeptas daržovėmis ir mocarela', category: 'KARŠTI_KIAULIENA', price: 6.00 },
  { id: '1704', name: 'Maltinis užkeptas morkomis ir mocarela', category: 'KARŠTI_KIAULIENA', price: 6.00 },
  { id: '1705', name: 'Maltinis užkeptas šv. morkomis ir mocarela', category: 'KARŠTI_KIAULIENA', price: 6.00 },
  { id: '1702', name: 'Maltinis užkeptas kepintais svogūnais ir pomidorų padažu', category: 'KARŠTI_KIAULIENA', price: 6.00 },
  { id: '1698', name: 'Naminis maltinis', category: 'KARŠTI_KIAULIENA', price: 5.40 },
  { id: '1923', name: 'Naminis maltinis baltame padaže', category: 'KARŠTI_KIAULIENA', price: 5.60 },
  { id: '2107', name: 'Naminis maltinis grietinės ir pomidorų padaže', category: 'KARŠTI_KIAULIENA', price: 5.60 },
  { id: '2017', name: 'Naminis maltinis grietinėlės saldžiarūgščiame padaže', category: 'KARŠTI_KIAULIENA', price: 5.60 },
  { id: '1898', name: 'Naminis maltinis morkų padaže', category: 'KARŠTI_KIAULIENA', price: 5.70 },
  { id: '1721', name: 'Maltinukai špinatų padaže', category: 'KARŠTI_KIAULIENA', price: 5.40 },
  { id: '1751', name: 'Maltinukai špinatų padaže 0,5', category: 'KARŠTI_KIAULIENA', price: 4.20 },
  { id: '1720', name: 'Maltinukai grietinės ir pomidorų padaže', category: 'KARŠTI_KIAULIENA', price: 5.40 },
  { id: '1753', name: 'Maltinukai grietinės ir pomidorų padaže 0,5', category: 'KARŠTI_KIAULIENA', price: 4.20 },
  { id: '1728', name: 'Maltinukai morkų ir žirnelių padaže', category: 'KARŠTI_KIAULIENA', price: 5.40 },
  { id: '1864', name: 'Maltinukai morkų ir žirnelių padaže 0,5', category: 'KARŠTI_KIAULIENA', price: 4.20 },
  { id: '1723', name: 'Maltinukai grybų padaže', category: 'KARŠTI_KIAULIENA', price: 5.40 },
  { id: '1749', name: 'Maltinukai grybų padaže 0,5', category: 'KARŠTI_KIAULIENA', price: 4.20 },
  { id: '1722', name: 'Maltinukai grietinėlės ir daržovių padaže', category: 'KARŠTI_KIAULIENA', price: 5.40 },
  { id: '1750', name: 'Maltinukai grietinėlės ir daržovių padaže 0,5', category: 'KARŠTI_KIAULIENA', price: 4.20 },
  { id: '1918', name: 'Maltinukai baltame padaže', category: 'KARŠTI_KIAULIENA', price: 5.40 },
  { id: '1951', name: 'Maltinukai baltame padaže 0,5', category: 'KARŠTI_KIAULIENA', price: 4.20 },
  { id: '1991', name: 'Maltinukai morkų padaže', category: 'KARŠTI_KIAULIENA', price: 5.40 },
  { id: '1992', name: 'Maltinukai morkų padaže 0,5', category: 'KARŠTI_KIAULIENA', price: 4.20 },
  { id: '1694', name: 'Suktinukas įdarytas morkomis ir svogūnais', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1542', name: 'Suktinukas įdarytas feta', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1942', name: 'Suktinukas įdarytas feta ir saulėje džiovintais pomidorais', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1696', name: 'Suktinukas įdarytas saulėje džiovintais pomidorais', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '2112', name: 'Suktinukas įdarytas slyvomis', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1734', name: 'Suktinukas įdarytas grybais ir sūriu', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1879', name: 'Suktinukas įdarytas daržovėmis', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1695', name: 'Suktinukas įdarytas šonine ir sūriu', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '2009', name: 'Troškinys su brokoliais', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1688', name: 'Troškinys su avinžirniais', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1563', name: 'Troškinys su daržovėmis ir grietinėle', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1939', name: 'Troškinys su saulėje džiovintais pomidorais', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1691', name: 'Troškinys su daržovėmis ir grybais', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1690', name: 'Troškinys su kepintais svogūnais ir grietine', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '2000', name: 'Troškinys su pupelėmis', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '2025', name: 'Troškinys su šparaginėmis pupelėmis ir pomidorų padažu', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '2001', name: 'Troškinys su pupelėmis ir daržovėmis', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1978', name: 'Troškinys su pievagrybiais', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1462', name: 'Zrazai įdaryti morkomis, baltame padaže', category: 'KARŠTI_KIAULIENA', price: 5.40 },
  { id: '1470', name: 'Zrazai įdaryti morkomis, baltame padaže 0,5', category: 'KARŠTI_KIAULIENA', price: 4.20 },
  { id: '1891', name: 'Zrazai daryti šonine ir sūriu, baltame padaže', category: 'KARŠTI_KIAULIENA', price: 5.40 },
  { id: '1892', name: 'Zrazai daryti šonine ir sūriu, baltame padaže 0,5', category: 'KARŠTI_KIAULIENA', price: 4.20 },
  { id: '1859', name: 'Zrazai įdaryti feta, baltame padaže', category: 'KARŠTI_KIAULIENA', price: 5.40 },
  { id: '1858', name: 'Zrazai įdaryti feta, baltame padaže 0,5', category: 'KARŠTI_KIAULIENA', price: 4.20 },
  { id: '1733', name: 'Zrazai įdaryti grybais ir sūriu, baltame padaže', category: 'KARŠTI_KIAULIENA', price: 5.40 },
  { id: '1754', name: 'Zrazai įdaryti grybais ir sūriu, baltame padaže 0,5', category: 'KARŠTI_KIAULIENA', price: 4.20 },
  { id: '1732', name: 'Zrazai įdaryti kiaušiniais, baltame padaže', category: 'KARŠTI_KIAULIENA', price: 5.40 },
  { id: '1755', name: 'Zrazai įdaryti kiaušiniais, baltame padaže 0,5', category: 'KARŠTI_KIAULIENA', price: 4.20 },
  { id: '1883', name: 'Zrazai įdaryti saulėje džiovintais pomidorais, baltame padaže', category: 'KARŠTI_KIAULIENA', price: 5.40 },
  { id: '1882', name: 'Zrazai įdaryti saulėje džiovintais pomidorais, baltame padaže 0,5', category: 'KARŠTI_KIAULIENA', price: 4.20 },
  { id: '1731', name: 'Zrazai įdaryti špinatais, baltame padaže', category: 'KARŠTI_KIAULIENA', price: 5.40 },
  { id: '1756', name: 'Zrazai įdaryti špinatais, baltame padaže 0,5', category: 'KARŠTI_KIAULIENA', price: 4.20 },
  { id: '2054', name: 'Kapoti kiaulienos kepsneliai', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1899', name: 'Karka su troškintais kopūstais', category: 'KARŠTI_KIAULIENA', price: 7.60 },
  { id: '2111', name: 'Kepsnys su traškia plutele, įdarytas minkštu sūriu ir saulėje dž.pomidorais', category: 'KARŠTI_KIAULIENA', price: 6.70 },
  { id: '2026', name: 'Makaronai su kiauliena', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1985', name: 'Sprandinės muštinis su marinuotais svogūnais', category: 'KARŠTI_KIAULIENA', price: 6.70 },
  { id: '2021', name: 'Nugarinės juostelės saldžiarūgščiame padaže', category: 'KARŠTI_KIAULIENA', price: 7.60 },
  { id: '2033', name: 'Nugarinės juostelės grybų padaže', category: 'KARŠTI_KIAULIENA', price: 7.60 },
  { id: '1938', name: 'Nugarinės kepsneliai grietinėlės ir sūrio padaže', category: 'KARŠTI_KIAULIENA', price: 7.60 },
  { id: '1730', name: 'Plovas', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1719', name: 'Rūkytos dešrelės su troškintais kopūstais', category: 'KARŠTI_KIAULIENA', price: 6.50 },
  { id: '1714', name: 'Sprandinės kepsnys užkeptas svogūnais pomidorų padaže', category: 'KARŠTI_KIAULIENA', price: 7.90 },
  { id: '1713', name: 'Sprandinės kepsnys užkeptas grybais', category: 'KARŠTI_KIAULIENA', price: 7.90 },
  { id: '1712', name: 'Sprandinės kepsnys užkeptas marinuotais svogūnais', category: 'KARŠTI_KIAULIENA', price: 7.90 },
  { id: '2053', name: 'Sprandinės kepsnys su karamelizuotais burokėliais', category: 'KARŠTI_KIAULIENA', price: 7.90 },
  { id: '2113', name: 'Sprandinės troškinys', category: 'KARŠTI_KIAULIENA', price: 7.40 },
  { id: '1727', name: 'Sprandinė BBQ', category: 'KARŠTI_KIAULIENA', price: 7.90 },
  { id: '2068', name: 'Sprandinė su troškintais kopūstais', category: 'KARŠTI_KIAULIENA', price: 7.90 },
  { id: '1546', name: 'Šašlykas', category: 'KARŠTI_KIAULIENA', price: 7.90 },
  { id: '1465', name: 'Šnicelis', category: 'KARŠTI_KIAULIENA', price: 5.40 },
  { id: '2032', name: 'Šoninė aluje', category: 'KARŠTI_KIAULIENA', price: 7.20 },
  { id: '1726', name: 'Šoninė BBQ', category: 'KARŠTI_KIAULIENA', price: 7.20 },
  { id: '2048', name: 'Šoninė su adžika', category: 'KARŠTI_KIAULIENA', price: 7.20 },
  { id: '1725', name: 'Šoninė su krienų padažu', category: 'KARŠTI_KIAULIENA', price: 7.40 },
  { id: '1957', name: 'Šoninė su marinuotais svogūnais', category: 'KARŠTI_KIAULIENA', price: 7.20 },
  { id: '1529', name: 'Šoninė su troškintais kopūstais', category: 'KARŠTI_KIAULIENA', price: 7.40 },
  { id: '1468', name: 'Šonkauliai', category: 'KARŠTI_KIAULIENA', price: 7.90 },
  { id: '1977', name: 'Šonkauliai su marinuotais svogūnais', category: 'KARŠTI_KIAULIENA', price: 7.90 },
  { id: '1693', name: 'Šonkauliai su troškintais kopūstais', category: 'KARŠTI_KIAULIENA', price: 7.90 },
  { id: '1849', name: 'Šonkauliai troškinti aluje', category: 'KARŠTI_KIAULIENA', price: 7.90 },
  { id: '1724', name: 'Šonkauliai BBQ', category: 'KARŠTI_KIAULIENA', price: 7.90 },
  { id: '1576', name: 'Tinginio balandėliai', category: 'KARŠTI_KIAULIENA', price: 6.80 },
  { id: '1577', name: 'Tinginio balandėliai 0,5', category: 'KARŠTI_KIAULIENA', price: 4.80 },
  { id: '2101', name: 'Traškios nugarinės juostelės', category: 'KARŠTI_KIAULIENA', price: 7.60 },
  { id: '1561', name: 'Troškinta kiauliena su kopūstais', category: 'KARŠTI_KIAULIENA', price: 6.50 },

  // VIŠTIENA
  { id: '1598', name: 'Baklažanas įdarytas vištiena', category: 'KARŠTI_VIŠTIENA', price: 4.80 },
  { id: '1970', name: 'Blauzdelės troškintos su grybais ir juoda duona', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '2040', name: 'Blauzdelės grybų padaže', category: 'KARŠTI_VIŠTIENA', price: 6.00 },
  { id: '2119', name: 'Kepsnys Cordon Bleu', category: 'KARŠTI_VIŠTIENA', price: 7.00 },
  { id: '1819', name: 'Cukinija įdaryta vištiena', category: 'KARŠTI_VIŠTIENA', price: 6.00 },
  { id: '2046', name: 'Filė maltinukas įdarytas feta traškia plutele', category: 'KARŠTI_VIŠTIENA', price: 6.60 },
  { id: '2069', name: 'Filė troškinys', category: 'KARŠTI_VIŠTIENA', price: 6.60 },
  { id: '2036', name: 'Filė vėrinukai', category: 'KARŠTI_VIŠTIENA', price: 6.70 },
  { id: '1861', name: 'Grill vištiena', category: 'KARŠTI_VIŠTIENA', price: 6.30 },
  { id: '2126', name: 'Guliašas', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '2039', name: 'Keptos blauzdelės', category: 'KARŠTI_VIŠTIENA', price: 6.00 },
  { id: '1770', name: 'Kijevo kotletas', category: 'KARŠTI_VIŠTIENA', price: 7.00 },
  { id: '1922', name: 'Kišenėlė įdaryta morkomis ir šonine', category: 'KARŠTI_VIŠTIENA', price: 7.00 },
  { id: '1893', name: 'Kišenėlė įdaryta varške ir šonine', category: 'KARŠTI_VIŠTIENA', price: 7.00 },
  { id: '1778', name: 'Lazanija', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '2027', name: 'Makaronai su daržovėmis ir vištiena', category: 'KARŠTI_VIŠTIENA', price: 6.30 },
  { id: '2114', name: 'Maltinis daržovių sūrio padaže', category: 'KARŠTI_VIŠTIENA', price: 5.60 },
  { id: '2052', name: 'Maltinis grybų padaže', category: 'KARŠTI_VIŠTIENA', price: 5.80 },
  { id: '2108', name: 'Plovas', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1822', name: 'Traški vištiena', category: 'KARŠTI_VIŠTIENA', price: 6.40 },
  { id: '2109', name: 'Traškus kepsnys su saldžiarūgščiu padažu', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '2104', name: 'Troškinys su pievagrybiais ir šonine', category: 'KARŠTI_VIŠTIENA', price: 6.60 },
  { id: '2082', name: 'Troškinys su kariu', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1538', name: 'Troškinys su vaisiais', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1826', name: 'Troškinys su džiovintais vaisiais', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1824', name: 'Troškinys su grietinėle ir sūriu', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1757', name: 'Troškinys su daržovėmis', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1825', name: 'Troškinys su grietinėle ir daržovėmis', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '2050', name: 'Troškinys su kukurūzais ir kokoso pienu', category: 'KARŠTI_VIŠTIENA', price: 6.60 },
  { id: '2003', name: 'Troškinys VYŠNIA', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1764', name: 'Maltinis', category: 'KARŠTI_VIŠTIENA', price: 5.40 },
  { id: '1769', name: 'Maltinis įdarytas špinatais', category: 'KARŠTI_VIŠTIENA', price: 5.60 },
  { id: '1765', name: 'Maltinis įdarytas feta', category: 'KARŠTI_VIŠTIENA', price: 5.60 },
  { id: '1766', name: 'Maltinis įdarytas morkomis', category: 'KARŠTI_VIŠTIENA', price: 5.60 },
  { id: '1768', name: 'Maltinis įdarytas saulėje džiovintais pomidorais', category: 'KARŠTI_VIŠTIENA', price: 5.60 },
  { id: '1767', name: 'Maltinis įdarytas šonine ir sūriu', category: 'KARŠTI_VIŠTIENA', price: 5.60 },
  { id: '1793', name: 'Maltinis morkų žirnelių padaže', category: 'KARŠTI_VIŠTIENA', price: 5.40 },
  { id: '1812', name: 'Maltinis įdarytas špinatais, apsuktas šonine', category: 'KARŠTI_VIŠTIENA', price: 5.70 },
  { id: '1570', name: 'Maltinis įdarytas feta, apsuktas šonine', category: 'KARŠTI_VIŠTIENA', price: 5.70 },
  { id: '1808', name: 'Maltinis įdarytas morkomis, apsuktas šonine', category: 'KARŠTI_VIŠTIENA', price: 5.70 },
  { id: '1810', name: 'Maltinis įdarytas šonine ir sūriu, apsuktas šonine', category: 'KARŠTI_VIŠTIENA', price: 5.70 },
  { id: '1813', name: 'Maltinis įdarytas grybais, apsuktas šonine', category: 'KARŠTI_VIŠTIENA', price: 5.70 },
  { id: '1809', name: 'Maltinis įdarytas saulėje džiovintais pomidorais, apsuktas šonine', category: 'KARŠTI_VIŠTIENA', price: 5.70 },
  { id: '1818', name: 'Maltinis užkeptas morkomis', category: 'KARŠTI_VIŠTIENA', price: 6.00 },
  { id: '1815', name: 'Maltinis užkeptas grybais', category: 'KARŠTI_VIŠTIENA', price: 6.00 },
  { id: '1817', name: 'Maltinis užkeptas daržovėmis', category: 'KARŠTI_VIŠTIENA', price: 6.00 },
  { id: '1780', name: 'Maltinis užkeptas ananasu', category: 'KARŠTI_VIŠTIENA', price: 6.30 },
  { id: '1814', name: 'Maltinis užkeptas marinuotais svogūnais', category: 'KARŠTI_VIŠTIENA', price: 6.00 },
  { id: '1816', name: 'Maltinis užkeptas svogūnais pomidorų padaže', category: 'KARŠTI_VIŠTIENA', price: 6.00 },
  { id: '1788', name: 'Maltinukai grietinės pomidorų padaže', category: 'KARŠTI_VIŠTIENA', price: 5.40 },
  { id: '1789', name: 'Maltinukai grietinės pomidorų padaže 0,5', category: 'KARŠTI_VIŠTIENA', price: 3.90 },
  { id: '1781', name: 'Maltinukai morkų ir žirnelių padaže', category: 'KARŠTI_VIŠTIENA', price: 5.40 },
  { id: '1783', name: 'Maltinukai morkų ir žirnelių padaže 0,5', category: 'KARŠTI_VIŠTIENA', price: 3.90 },
  { id: '1961', name: 'Maltinukai žirnelių padaže', category: 'KARŠTI_VIŠTIENA', price: 5.40 },
  { id: '1794', name: 'Maltinukai žirnelių padaže 0,5', category: 'KARŠTI_VIŠTIENA', price: 3.90 },
  { id: '1790', name: 'Maltinukai grybų padaže', category: 'KARŠTI_VIŠTIENA', price: 5.40 },
  { id: '1792', name: 'Maltinukai grybų padaže 0,5', category: 'KARŠTI_VIŠTIENA', price: 3.90 },
  { id: '1784', name: 'Maltinukai grietinėlės ir daržovių padaže', category: 'KARŠTI_VIŠTIENA', price: 5.40 },
  { id: '1785', name: 'Maltinukai grietinėlės ir daržovių padaže 0,5', category: 'KARŠTI_VIŠTIENA', price: 3.90 },
  { id: '1917', name: 'Maltinukai grietinėlės sūrio padaže', category: 'KARŠTI_VIŠTIENA', price: 5.40 },
  { id: '1772', name: 'Maltinukai grietinėlės sūrio padaže 0,5', category: 'KARŠTI_VIŠTIENA', price: 3.90 },
  { id: '2014', name: 'Maltinukai saldžiarūgščiame padaže', category: 'KARŠTI_VIŠTIENA', price: 5.40 },
  { id: '2015', name: 'Maltinukai saldžiarūgščiame padaže 0,5', category: 'KARŠTI_VIŠTIENA', price: 3.90 },
  { id: '1998', name: 'Maltinukai morkų padaže', category: 'KARŠTI_VIŠTIENA', price: 5.40 },
  { id: '1999', name: 'Maltinukai morkų padaže 0,5', category: 'KARŠTI_VIŠTIENA', price: 3.90 },
  { id: '1786', name: 'Maltinukai špinatų padaže', category: 'KARŠTI_VIŠTIENA', price: 5.40 },
  { id: '1787', name: 'Maltinukai špinatų padaže 0,5', category: 'KARŠTI_VIŠTIENA', price: 3.90 },
  { id: '1827', name: 'Maltinukai baltame padaže', category: 'KARŠTI_VIŠTIENA', price: 5.40 },
  { id: '1828', name: 'Maltinukai baltame padaže 0,5', category: 'KARŠTI_VIŠTIENA', price: 3.90 },
  { id: '1797', name: 'Zrazai įdaryti saulėje džiovintais pomidorais, baltame padaže', category: 'KARŠTI_VIŠTIENA', price: 5.40 },
  { id: '1798', name: 'Zrazai įdaryti saulėje džiovintais pomidorais, baltame padaže 0,5', category: 'KARŠTI_VIŠTIENA', price: 3.90 },
  { id: '1931', name: 'Zrazai įdaryti grybais, rausvame padaže', category: 'KARŠTI_VIŠTIENA', price: 5.40 },
  { id: '1932', name: 'Zrazai įdaryti grybais, rausvame padaže 0,5', category: 'KARŠTI_VIŠTIENA', price: 3.90 },
  { id: '1807', name: 'Zrazai įdaryti grybais, baltame padaže', category: 'KARŠTI_VIŠTIENA', price: 5.40 },
  { id: '1805', name: 'Zrazai įdaryti grybais, baltame padaže 0,5', category: 'KARŠTI_VIŠTIENA', price: 3.90 },
  { id: '1799', name: 'Zrazai įdaryti feta, baltame padaže', category: 'KARŠTI_VIŠTIENA', price: 5.40 },
  { id: '1800', name: 'Zrazai įdaryti feta, baltame padaže 0,5', category: 'KARŠTI_VIŠTIENA', price: 3.90 },
  { id: '1803', name: 'Zrazai įdaryti špinatais, baltame padaže', category: 'KARŠTI_VIŠTIENA', price: 5.40 },
  { id: '1804', name: 'Zrazai įdaryti špinatais, baltame padaže 0,5', category: 'KARŠTI_VIŠTIENA', price: 3.90 },
  { id: '1795', name: 'Zrazai įdaryti morkomis, baltame padaže', category: 'KARŠTI_VIŠTIENA', price: 5.40 },
  { id: '1796', name: 'Zrazai įdaryti morkomis, baltame padaže 0,5', category: 'KARŠTI_VIŠTIENA', price: 3.90 },
  { id: '1801', name: 'Zrazai įdaryti šonine ir sūriu, baltame padaže', category: 'KARŠTI_VIŠTIENA', price: 5.40 },
  { id: '1802', name: 'Zrazai įdaryti šonine ir sūriu, baltame padaže 0,5', category: 'KARŠTI_VIŠTIENA', price: 3.90 },
  { id: '1820', name: 'Kepenėlės troškintos grietinėlėje', category: 'KARŠTI_VIŠTIENA', price: 5.40 },
  { id: '1774', name: 'Kepsnys užkeptas grybais', category: 'KARŠTI_VIŠTIENA', price: 6.30 },
  { id: '1846', name: 'Kepsnys užkeptas morkomis', category: 'KARŠTI_VIŠTIENA', price: 6.30 },
  { id: '2118', name: 'Kepsnys užkeptas obuoliais', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1896', name: 'Kepsnys užkeptas ananasu', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1776', name: 'Kepsnys užkeptas grybais', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1773', name: 'Kepsnys užkeptas marinuotais svogūnais', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1775', name: 'Kepsnys užkeptas svogūnais su pomidorų padažu', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1777', name: 'Kepsnys užkeptas šv.morkomis', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1771', name: 'Filė kapotinis', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1597', name: 'Vištiena saldžiarūgštė', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1779', name: 'Vištiena kinietiškai', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1855', name: 'Širdelių troškinys', category: 'KARŠTI_VIŠTIENA', price: 5.40 },
  { id: '2109', name: 'Traškus kepsnys', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1759', name: 'Suktinis įdarytas šonine ir sūriu', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1758', name: 'Suktinukas įdarytas morkomis', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '2090', name: 'Suktinukas įdarytas spanguolėmis', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1601', name: 'Suktinukas įdarytas feta', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1929', name: 'Suktinukas įdarytas su šonine', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '2115', name: 'Suktinukas įdarytas su abrikosais', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1763', name: 'Suktinukas įdarytas grybais', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1760', name: 'Suktinukas įdarytas saulėje džiovintais pomidorais', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1762', name: 'Suktinukas įdarytas špinatais', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1821', name: 'Teriyaki iešmeliai', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '1569', name: 'Vėrinukai', category: 'KARŠTI_VIŠTIENA', price: 6.50 },
  { id: '2076', name: 'Vištiena BBQ', category: 'KARŠTI_VIŠTIENA', price: 6.40 },
  { id: '1823', name: 'Vištiena Teriyaki', category: 'KARŠTI_VIŠTIENA', price: 6.40 },

  // KALAKUTIENA
  { id: '2117', name: 'Maltinukai grybų padaže', category: 'KARŠTI_KALAKUTIENA', price: 5.80 },
  { id: '2103', name: 'Maltinukai grybų padaže 0,5', category: 'KARŠTI_KALAKUTIENA', price: 3.90 },
  { id: '2022', name: 'Maltinukai grietinės ir morkų padaže', category: 'KARŠTI_KALAKUTIENA', price: 5.80 },
  { id: '2023', name: 'Maltinukai grietinės ir morkų padaže 0,5', category: 'KARŠTI_KALAKUTIENA', price: 3.90 },
  { id: '2074', name: 'Maltinis įdarytas špinatais', category: 'KARŠTI_KALAKUTIENA', price: 5.80 },
  { id: '2102', name: 'Maltinukai morkų padaže', category: 'KARŠTI_KALAKUTIENA', price: 5.80 },
  { id: '2024', name: 'Troškinys su grybais ir grietinėle', category: 'KARŠTI_KALAKUTIENA', price: 6.60 },
  { id: '2028', name: 'Troškinys su pomidorais', category: 'KARŠTI_KALAKUTIENA', price: 6.60 },
  { id: '1571', name: 'Guliašas', category: 'KARŠTI_KALAKUTIENA', price: 6.60 },
  { id: '2002', name: 'Saldžiarūgštis troškinys', category: 'KARŠTI_KALAKUTIENA', price: 6.70 },

  // ŽUVIS
  { id: '2044', name: 'Ešerys užkeptas pomidorais', category: 'KARŠTI_ŽUVIS', price: 7.00 },
  { id: '2045', name: 'Ešerys užkeptas pomidorais', category: 'KARŠTI_ŽUVIS', price: 4.50 },
  { id: '1890', name: 'Maltinis įdarytas česnakiniu sviestu traškia plutele', category: 'KARŠTI_ŽUVIS', price: 6.50 },
  { id: '2092', name: 'Kepta lydeka su svogūnais', category: 'KARŠTI_ŽUVIS', price: 6.50 },
  { id: '2019', name: 'Lašišos maltinis įdarytas sviestu traškia plutele', category: 'KARŠTI_ŽUVIS', price: 6.50 },
  { id: '1945', name: 'Lašišos maltinis įdarytas špinatais traškia plutele', category: 'KARŠTI_ŽUVIS', price: 6.50 },
  { id: '1982', name: 'Lašišos maltinukai kaparėlių padaže', category: 'KARŠTI_ŽUVIS', price: 6.50 },
  { id: '2130', name: 'Lašišos maltinukai kaparėlių padaže 0,5', category: 'KARŠTI_ŽUVIS', price: 4.80 },
  { id: '2121', name: 'Lašišos kapotiniai', category: 'KARŠTI_ŽUVIS', price: 6.00 },
  { id: '2122', name: 'Lašišos kapotiniai 0,5', category: 'KARŠTI_ŽUVIS', price: 3.20 },
  { id: '1603', name: 'Lašišos kepsnys', category: 'KARŠTI_ŽUVIS', price: 8.20 },
  { id: '1502', name: 'Lašišos kepsnys su daržovėmis', category: 'KARŠTI_ŽUVIS', price: 8.20 },
  { id: '1525', name: 'Lašišos maltinukai', category: 'KARŠTI_ŽUVIS', price: 6.20 },
  { id: '1527', name: 'Lašišos maltinukai', category: 'KARŠTI_ŽUVIS', price: 4.00 },
  { id: '2120', name: 'Lydekos kepsnys užkeptas morkomis', category: 'KARŠTI_ŽUVIS', price: 6.50 },
  { id: '1979', name: 'Makaronai su lašiša', category: 'KARŠTI_ŽUVIS', price: 7.20 },
  { id: '1553', name: 'Maltinis traškia plutele', category: 'KARŠTI_ŽUVIS', price: 6.50 },
  { id: '1495', name: 'Traški lydeka', category: 'KARŠTI_ŽUVIS', price: 6.50 },
  { id: '1610', name: 'Traški tilapija', category: 'KARŠTI_ŽUVIS', price: 6.50 },
  { id: '2135', name: 'Traškus menkės kepsnys', category: 'KARŠTI_ŽUVIS', price: 6.60 },
  { id: '2034', name: 'Upėtakio didkepsnis', category: 'KARŠTI_ŽUVIS', price: 7.30 },
  { id: '1829', name: 'Lydekos kepnys užkeptas pomidorais', category: 'KARŠTI_ŽUVIS', price: 6.50 },
  { id: '1830', name: 'Maltinukai morkų žirnelių padaže', category: 'KARŠTI_ŽUVIS', price: 5.90 },
  { id: '1831', name: 'Maltinukai morkų žirnelių padaže 0,5', category: 'KARŠTI_ŽUVIS', price: 4.30 },
  { id: '1836', name: 'Maltinukai baltame padaže', category: 'KARŠTI_ŽUVIS', price: 5.90 },
  { id: '1837', name: 'Maltinukai baltame padaže 0,5', category: 'KARŠTI_ŽUVIS', price: 4.30 },
  { id: '1948', name: 'Maltinukai morkų padaže', category: 'KARŠTI_ŽUVIS', price: 5.90 },
  { id: '1947', name: 'Maltinukai morkų padaže 0,5', category: 'KARŠTI_ŽUVIS', price: 4.30 },
  { id: '1832', name: 'Maltinukai daržovių padaže', category: 'KARŠTI_ŽUVIS', price: 5.90 },
  { id: '1833', name: 'Maltinukai daržovių padaže 0,5', category: 'KARŠTI_ŽUVIS', price: 4.30 },
  { id: '1834', name: 'Maltinukai špinatų padaže', category: 'KARŠTI_ŽUVIS', price: 5.90 },
  { id: '1835', name: 'Maltinukai špinatų padaže 0,5', category: 'KARŠTI_ŽUVIS', price: 4.30 },
  { id: '1954', name: 'Maltinukai žirnelių padaže', category: 'KARŠTI_ŽUVIS', price: 5.90 },
  { id: '1953', name: 'Maltinukai žirnelių padaže 0,5', category: 'KARŠTI_ŽUVIS', price: 4.30 },
  { id: '1585', name: 'Žuvis kinietiškai', category: 'KARŠTI_ŽUVIS', price: 6.50 },
  { id: '1841', name: 'Maltinis įdarytas feta traškia plutele', category: 'KARŠTI_ŽUVIS', price: 6.20 },
  { id: '1496', name: 'Maltinukai', category: 'KARŠTI_ŽUVIS', price: 5.90 },
  { id: '1497', name: 'Maltinukai 0,5', category: 'KARŠTI_ŽUVIS', price: 4.30 },
  { id: '1901', name: 'Šnicelis su kreminiu agurkiniu padažu', category: 'KARŠTI_ŽUVIS', price: 6.50 },
  { id: '2127', name: 'Kroketas įdarytas grybais su česnakiniu padažu', category: 'KARŠTI_ŽUVIS', price: 6.50 },
  { id: '1914', name: 'Užkepėlė', category: 'KARŠTI_ŽUVIS', price: 6.50 },
  { id: '1782', name: 'Lydeka alaus tešloje', category: 'KARŠTI_ŽUVIS', price: 6.50 },
  { id: '2128', name: 'Lydeka užkepta obuoliais ir porais', category: 'KARŠTI_ŽUVIS', price: 6.50 },

  // KITI
  { id: '2117', name: 'Maltinukai grybų padaže', category: 'KITI', price: 5.80 },
  { id: '2103', name: 'Maltinukai grybų padaže 0,5', category: 'KITI', price: 3.90 },
  { id: '2022', name: 'Maltinukai grietinės ir morkų padaže', category: 'KITI', price: 5.80 },
  { id: '2023', name: 'Maltinukai grietinės ir morkų padaže 0,5', category: 'KITI', price: 3.90 },
  { id: '2074', name: 'Maltinis įdarytas špinatais', category: 'KITI', price: 5.80 },
  { id: '2102', name: 'Maltinukai morkų padaže', category: 'KITI', price: 5.80 },
  { id: '2024', name: 'Troškinys su grybais ir grietinėle', category: 'KITI', price: 6.60 },
  { id: '2028', name: 'Troškinys su pomidorais', category: 'KITI', price: 6.60 },
  { id: '1571', name: 'Guliašas', category: 'KITI', price: 6.60 },
  { id: '2002', name: 'Saldžiarūgštis troškinys', category: 'KITI', price: 6.70 },

  // DESERTAI
  { id: '1522', name: 'Chia desertas', category: 'DESERTAI', price: 1.50 },
  { id: '1523', name: 'Graikiško jogurto desertas', category: 'DESERTAI', price: 1.50 },
  { id: '1582', name: 'Karštas braunis', category: 'DESERTAI', price: 3.00 },
  { id: '1514', name: 'Karštas braunis su ledais', category: 'DESERTAI', price: 3.50 },
  { id: '1516', name: 'Ledai', category: 'DESERTAI', price: 3.00 },
  { id: '1971', name: 'Ledų rutuliukas', category: 'DESERTAI', price: 0.50 },
  { id: '1921', name: 'Morkų pyragas', category: 'DESERTAI', price: 2.00 },
  { id: '1515', name: 'Obuolių pyragas', category: 'DESERTAI', price: 3.00 },
  { id: '1517', name: 'Panna cotta su braškių tyre', category: 'DESERTAI', price: 1.50 },
  { id: '1518', name: 'Panna cotta su mangų tyre', category: 'DESERTAI', price: 1.50 },
  { id: '1519', name: 'Plaktos varškės desertas', category: 'DESERTAI', price: 2.00 },
  { id: '1609', name: 'Sloksniuotas desertas', category: 'DESERTAI', price: 3.00 },
  { id: '1595', name: 'Snikerinis pyragas', category: 'DESERTAI', price: 3.00 },
  { id: '2030', name: 'Šokoladinis bananų pyragas', category: 'DESERTAI', price: 2.50 },
  { id: '1521', name: 'Žėlė', category: 'DESERTAI', price: 1.50 },
  { id: '1520', name: 'Žėlė su plakta grietinėle', category: 'DESERTAI', price: 1.70 },

  // GĖRIMAI
  { id: '2084', name: '7 UP 0,5', category: 'GĖRIMAI', price: 2.00 },
  { id: '1507', name: 'Arbata', category: 'GĖRIMAI', price: 1.00 },
  { id: '1456', name: 'Energetinis gėrimas', category: 'GĖRIMAI', price: 2.00 },
  { id: '1444', name: 'Gira', category: 'GĖRIMAI', price: 1.00 },
  { id: '1504', name: 'Capuccino', category: 'GĖRIMAI', price: 2.00 },
  { id: '1501', name: 'Juoda kava', category: 'GĖRIMAI', price: 1.60 },
  { id: '1505', name: 'Latte', category: 'GĖRIMAI', price: 2.00 },
  { id: '1503', name: 'Kava su pienu', category: 'GĖRIMAI', price: 1.80 },
  { id: '1445', name: 'Kefyras', category: 'GĖRIMAI', price: 1.00 },
  { id: '2100', name: 'Kisielius', category: 'GĖRIMAI', price: 1.00 },
  { id: '1442', name: 'Kompotas', category: 'GĖRIMAI', price: 1.00 },
  { id: '2081', name: 'Mirinda', category: 'GĖRIMAI', price: 2.00 },
  { id: '2106', name: 'Norte gazuotas 0,5', category: 'GĖRIMAI', price: 1.40 },
  { id: '2089', name: 'Norte negazuotas 0,6', category: 'GĖRIMAI', price: 1.40 },
  { id: '2083', name: 'Pepsi 0,5', category: 'GĖRIMAI', price: 2.00 },
  { id: '1447', name: 'Apelsinų sultys', category: 'GĖRIMAI', price: 1.00 },
  { id: '1448', name: 'Multivitaminų sultys', category: 'GĖRIMAI', price: 1.00 },
  { id: '1581', name: 'Vaikiškos sultys su šiaudeliu', category: 'GĖRIMAI', price: 1.00 },
  { id: '1446', name: 'Pomidorų sultys', category: 'GĖRIMAI', price: 1.00 },
  { id: '1449', name: 'Šviežios morkų sultys', category: 'GĖRIMAI', price: 2.50 },
  { id: '1975', name: 'Vilkmergės nealkoholinis alus', category: 'GĖRIMAI', price: 3.00 }
]; 